
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - ./wireguard/.env
    environment:
      - SERVERURL=${PUBLIC_IP}
    volumes:
      - ./config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

  cockpit:
    image: agentejo/cockpit
    container_name: cockpit
    ports:
      - "8080:80"
